# Generated by Django 5.0.1 on 2024-04-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_abilities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='dormitory',
            field=models.CharField(blank=True, choices=[('ABUBAKAR', 'ABUBAKAR'), ('AISHA', 'AISHA'), ('ALI', 'ALI'), ('AANNEX HADIJAHLI', 'ANNEX HADIJAH'), ('FAROOQ', 'FAROOQ'), ('HADIJAH', 'HADIJAH'), ('UTHUMAN', 'UTHUMAN'), ('ZAHARAH', 'ZAHARAH')], default='ABUBAKAR', max_length=255, null=True, verbose_name='المهجع'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('p1', 'p1'), ('p2', 'p2'), ('p3', 'p3'), ('p4', 'p4'), ('p5', 'p5'), ('p6', 'p6'), ('p7', 'p7'), ('NURS', 'NURS'), ('CHOICE', 'CHOICE')], default='CHOICE', max_length=255, null=True, verbose_name='المرحلة - LEVEL'),
        ),
        migrations.AlterField(
            model_name='student',
            name='quran_memorization',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], default='0', max_length=255, null=True, verbose_name='مقدار الحفظ من القرآن'),
        ),
        migrations.AlterField(
            model_name='student',
            name='residence_status',
            field=models.CharField(blank=True, choices=[('خارجي', 'خارجي'), ('داخلي', 'داخلي')], default='داخلي', max_length=255, null=True, verbose_name='السكن داخلي / خارجي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor_no',
            field=models.IntegerField(blank=True, max_length=255, null=True, verbose_name="رقم الكافل - SPONSOR'S NO"),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsorship_source',
            field=models.CharField(blank=True, choices=[('الهيئة', 'الهيئة'), ('بيت الزكاة', 'بيت الزكاة')], default='الهيئة', max_length=255, null=True, verbose_name='جهة الكفالة الهيئة/بيت الزكاة - SPONSORSHIP IICO OR ZAKAT'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsorship_status',
            field=models.CharField(blank=True, choices=[('CONTINUED', 'CONTINUED'), ('DROPPED', 'DROPPED')], default='CONTINUED', max_length=255, null=True, verbose_name='الكفالة مستمرة أم توقف - SPONSORSHIP CONTINUE OR STOP'),
        ),
    ]
