# Generated by Django 5.0.1 on 2024-04-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_student_class_name_alter_student_dormitory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sponsor_no',
            field=models.IntegerField(blank=True, null=True, verbose_name="رقم الكافل - SPONSOR'S NO"),
        ),
    ]
