# Generated by Django 5.0.1 on 2024-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_sponsor_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='system',
            field=models.CharField(blank=True, choices=[('P.D', 'P.D'), ('P.B', 'P.B'), ('TEACHER', 'TEACHER'), ('COM', 'COM'), ('DIRECTOR IICO', 'DIRECTOR IICO')], default='CHOICE', max_length=255, null=True, verbose_name='النظام - system'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dormitory',
            field=models.CharField(blank=True, choices=[('ABUBAKAR', 'ABUBAKAR'), ('AISHA', 'AISHA'), ('ALI', 'ALI'), ('AANNEX HADIJAHLI', 'ANNEX HADIJAH'), ('FAROOQ', 'FAROOQ'), ('HADIJAH', 'HADIJAH'), ('UTHUMAN', 'UTHUMAN'), ('ZAHARAH', 'ZAHARAH'), ('HOME', 'HOME'), ('OUT', 'OUT')], default='ABUBAKAR', max_length=255, null=True, verbose_name='المهجع'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('p1', 'p1'), ('p2', 'p2'), ('p3', 'p3'), ('p4', 'p4'), ('p5', 'p5'), ('p6', 'p6'), ('p7', 'p7'), ('NURS', 'NURS'), ('OUT', 'OUT'), ('CHOICE', 'CHOICE')], default='CHOICE', max_length=255, null=True, verbose_name='المرحلة - LEVEL'),
        ),
    ]
