from django.db import models

class Student(models.Model):
    name = models.CharField(max_length=255, verbose_name="الاسم - NAME")
    arabic_name = models.CharField(max_length=255, verbose_name="الاسم عربي")
    account_no = models.CharField(max_length=255, verbose_name="رقم الحساب - ACCOUNT NO")
    account_holder_name = models.CharField(max_length=255, verbose_name="اسم صاحب الحساب")
    orphan_no = models.CharField(max_length=255, verbose_name="رقم اليتيم - ORPHAN NO")
    sponsor_no = models.CharField(max_length=255, verbose_name="رقم الكافل - SPONSOR'S NO")
    date_of_birth = models.DateField(verbose_name="تاريخ الميلاد - DATE OF BIRTH")
    date_of_death = models.DateField(verbose_name="تاريخ الوفاة - DATE OF DEATH", blank=True, null=True)
    school = models.CharField(max_length=255, verbose_name="المدرسة - SCHOOL")
    level = models.CharField(max_length=255, verbose_name="المرحلة - LEVEL")
    class_name = models.CharField(max_length=255, verbose_name="الصف - CLASS")
    quran_memorization = models.CharField(max_length=255, verbose_name="مقدار الحفظ من القرآن")
    talents = models.CharField(max_length=255, verbose_name="المواهب")
    abilities = models.CharField(max_length=255, verbose_name="القدرات")
    residence_status = models.CharField(max_length=255, verbose_name="السكن داخلي / خارجي")
    dormitory = models.CharField(max_length=255, verbose_name="المهجع")
    sponsorship_status = models.CharField(max_length=255, verbose_name="الكفالة مستمرة أم توقف - SPONSORSHIP CONTINUE OR STOP")
    sponsorship_source = models.CharField(max_length=255, verbose_name="جهة الكفالة الهيئة/بيت الزكاة - SPONSORSHIP IICO OR ZAKAT")
    last_payment = models.CharField(max_length=255, verbose_name="آخر صرفية استلمها - LAST PAYMENT")
    date_received = models.DateField(verbose_name="تاريخ الاستلام- DATE OF RECEIVING")
    district = models.CharField(max_length=255, verbose_name="المحافظة - DISTRICT")
    area = models.CharField(max_length=255, verbose_name="المنطقة - AREA")
    guardian = models.CharField(max_length=255, verbose_name="ولي الأمر - GUARDIAN")
    phone_no = models.CharField(max_length=255, verbose_name="رقم الهاتف - PHONE NO")
    whatsapp_no = models.CharField(max_length=255, verbose_name="رقم الواتس - WHATSAPP")
    other_no = models.CharField(max_length=255, verbose_name="رقم آخر - OTHER NO")
    attachments = models.CharField(max_length=255, verbose_name="المرفقات - ATTACHEMENTS")
    weight = models.CharField(max_length=255, verbose_name="الوزن")
    height = models.CharField(max_length=255, verbose_name="الطول")
    shoe_size = models.CharField(max_length=255, verbose_name="مقاس الحذاء")
    thobe_size = models.CharField(max_length=255, verbose_name="مقاس الجلابية")
    guardian_id_no = models.CharField(max_length=255, verbose_name="رقم هوية ولي الأمر")
    health_status = models.CharField(max_length=255, verbose_name="الحالة الصحية")
    quarterly_evaluation = models.CharField(max_length=255, verbose_name="التقدير الفصلي")
    educational_level = models.CharField(max_length=255, verbose_name="المستوى التعليمي")
    registrar_notes = models.CharField(max_length=255, verbose_name="ملاحظات المسجل")
    director_notes = models.CharField(max_length=255, verbose_name="ملاحظات المدير")
    school_notes = models.CharField(max_length=255, verbose_name="ملاحظات المدرسة")
    tuition_fees = models.CharField(max_length=255, verbose_name="الرسوم الدراسية")
    paid_amount = models.CharField(max_length=255, verbose_name="المدفوع")
    payment_date = models.DateField(verbose_name="تاريخ الدفع")
    bank_notification_no = models.CharField(max_length=255, verbose_name="رقم الإشعار البنكي")
    balance = models.CharField(max_length=255, verbose_name="الباقي")
    services = models.CharField(max_length=255, verbose_name="الخدمات")

    def __str__(self):
        return self.name
